# runs ut and nuts for SDR, plus the nuts from plugin-source

name: tests
on:
  push:
    paths-ignore:
      - 'test/nuts/perfResults/**'
    branches-ignore: [main]
  workflow_dispatch:

jobs:
  unit-tests:
    uses: salesforcecli/github-workflows/.github/workflows/unitTest.yml@ew/retry-wrapper
  nuts:
    needs: unit-tests
    uses: salesforcecli/github-workflows/.github/workflows/nut.yml@ew/retry-wrapper
    secrets: inherit
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
    with:
      os: ${{ matrix.os }}
